---
title: "Baboon Diet Example"
author: "karltayeb"
date: "2022-03-16"
output:
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '#>',
  message=FALSE, warning=FALSE
)
```

```{r load.results}
library(gseasusie)
library(ggplot2)
library(tidyverse)
library(targets)

tar_load(baboon_diet_enrichment_summary)
results <- baboon_diet_enrichment_summary
```

```{r test, eval=FALSE}
res <- results$enrichment_summary[[2]]
res <- res %>%
  mutate(pval_marginal = 2*pnorm(-abs(effect_marginal/effect_se_marginal))) %>%
  mutate(pval_residual = 2*pnorm(-abs(effect_residual/effect_se_residual)))

res %>% gseasusie::enrichment_volcano2()
res %>% gseasusie::residual_enrichment_histogram2()
res %>% gseasusie:::static_table()
```

```{r experiment.level.results, results='asis'}
results <- results %>% arrange(experiment, ptop, db)
experiments <- results$experiment %>% unique()

for(this_experiment in experiments){
  cat('\n')
  cat('##', this_experiment)

  sub_res <- results %>% filter(experiment == this_experiment)

  N <- dim(sub_res)[1]
  for (i in 1:N){
    this_db <- sub_res$db[[i]]
    this_ptop <- sub_res$ptop[[i]]
    res <- sub_res$enrichment_summary[[i]]

    cat("\n") 
    cat("### prop genes = ", this_ptop, ', db = ', this_db, "\n") # Create second level headings with the names.
    volcano <- res %>% gseasusie::enrichment_volcano2()
    hist <- res %>% filter(overlap > 0) %>% residual_enrichment_histogram2() 
    print(volcano)
    print(hist)
    cat("\n\n")
    print(gseasusie:::static_table(res))
  }
}
```
