---
title: "Deng et al. Logistic SuSiE GSEA"
author: "karltayeb"
date: "2022-04-03"
output:
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(
  root.dir = '/project2/gilad/ktayeb/logistic-susie-gsea/'
)
knitr::opts_chunk$set(
  comment = '',
  message=FALSE, warning=FALSE,
  root.dir = '/project2/gilad/ktayeb/logistic-susie-gsea/'
)
```

## Overview

We report gene set enrichment analysis of the topics from Jason's NMF and SNMF of the Deng et al. data set. 

For each topic we construct a binary gene list by thresholding on local false sign rates output from `flash`. Here, I pick $lfsr} <- 1e-5$.



```{r load, message=FALSE, results='hide'}
#library(GSEABenchmarkeR)
#library(EnrichmentBrowser)
library(susieR)
library(DT)
library(kableExtra)
library(tidyverse)
library(Matrix)

source('code/load_gene_sets.R')
source('code/utils.R')
source('code/logistic_susie_vb.R')

#source('code/latent_logistic_susie.R')
```

```{r load.data}
# load nmf models
nmf <- readRDS('data/deng/nmf.rds')
snmf <- readRDS('data/deng/snmf.rds')

# load genesets
gobp <- loadGeneSetX('geneontology_Biological_Process', min.size=50)  # just huge number of gene sets
#gobp_nr <- loadGeneSetX('geneontology_Biological_Process_noRedundant', min.size=1)
gomf <- loadGeneSetX('geneontology_Molecular_Function', min.size=1)
kegg <- loadGeneSetX('pathway_KEGG', min.size=1)
#reactome <- loadGeneSetX('pathway_Reactome', min.size=1)
#wikipathway_cancer <- loadGeneSetX('pathway_Wikipathway_cancer', min.size=1)
#wikipathway <- loadGeneSetX('pathway_Wikipathway', min.size=1)

genesets <- list(
  gobp=gobp,
  #gobp_nr=gobp_nr,
  gomf=gomf,
  kegg=kegg
  #reactome=reactome,
  #wikipathway_cancer=wikipathway_cancer,
  #wikipathway=wikipathway
)
```

```{r prep.gene.list}
convert_labels <- function(y, from='SYMBOL', to='ENTREZID'){
  hs <- org.Hs.eg.db::org.Hs.eg.db
  
  gene_symbols <- names(y)
  if(from == 'SYMBOL'){
    gene_symbols <- purrr::map_chr(gene_symbols, toupper)
    names(y) <- gene_symbols
  }
  symbol2entrez <- AnnotationDbi::select(hs, keys=gene_symbols, columns=c(to, from), keytype = from)
  symbol2entrez <- symbol2entrez[!duplicated(symbol2entrez[[from]]),]
  symbol2entrez <- symbol2entrez[!is.na(symbol2entrez[[to]]),]
  symbol2entrez <- symbol2entrez[!is.na(symbol2entrez[[from]]),]
  rownames(symbol2entrez) <- symbol2entrez[[from]]
  ysub <- y[names(y) %in% symbol2entrez[[from]]]
  names(ysub) <- symbol2entrez[names(ysub),][[to]]
  return(ysub)
}
convert_labels = partial(convert_labels, from='SYMBOL')

#' makes a binary with threshold, convert labels
get_y = function(L, thresh){
  y <- convert_labels(L <= thresh) %>% 
    {mode(.) <- "integer"; .}
  return(y)
}
```

```{r functions}
#' fit logistic susie, and hypergeometric test
do_logistic_susie = function(y, db, susie.args=NULL){
  gs <- genesets[[db]]
  u <- process_input(gs$X, y)  # subset to common genes
  
  if(is.null(susie.args)){
    susie.args = list(
      L=10, init.intercept=0, verbose=1, maxit=100, standardize=TRUE)
  }
  
  logistic.susie(u$X, u$y, L=1)
  vb.fit <- exec(logistic.susie, u$X, u$y, !!!susie.args)

  #' hypergeometric test
  ora <- tibble(
    geneSet = colnames(u$X),
    geneListSize = sum(u$y),
    geneSetSize = colSums(u$X),
    overlap = (u$y %*% u$X)[1,],
    nGenes = length(u$y),
    propInList = overlap / geneListSize,
    propInSet = overlap / geneSetSize,
    oddsRatio = (overlap / (geneListSize - overlap)) / (
      (geneSetSize - overlap) / (nGenes - geneSetSize + overlap)),
    pValueHypergeometric = phyper(
      overlap-1, geneListSize, nGenes - geneListSize, geneSetSize, lower.tail= FALSE),
    db = db
  ) %>% 
  left_join(gs$geneSet$geneSetDes)
  return(list(fit = vb.fit, ora = ora, db=db))
}

get_credible_set_summary = function(res){
  gs <- genesets[[res$db]]
  #' report top 50 elements in cs
  beta <- t(res$fit$mu) %>%
    data.frame() %>%
    rownames_to_column(var='geneSet') %>%
    rename_with(~str_replace(., 'X', 'L')) %>%
    rename(L1 = 2) %>%  # rename deals with L=1 case
    pivot_longer(starts_with('L'), names_to='component', values_to = 'beta') 
  se <- t(sqrt(res$fit$mu2 - res$fit$mu^2)) %>%
     data.frame() %>%
      rownames_to_column(var='geneSet') %>%
      rename_with(~str_replace(., 'X', 'L')) %>%
      rename(L1 = 2) %>%  # rename deals with L=1 case
      pivot_longer(starts_with('L'), names_to='component', values_to = 'beta.se')
  
  credible.set.summary <- t(res$fit$alpha) %>%
    data.frame() %>%
    rownames_to_column(var='geneSet') %>%
    rename_with(~str_replace(., 'X', 'L')) %>%
    rename(L1 = 2) %>%  # rename deals with L=1 case
    pivot_longer(starts_with('L'), names_to='component', values_to = 'alpha') %>%
    left_join(beta) %>%
    left_join(se) %>%
    arrange(component, desc(alpha)) %>%
    dplyr::group_by(component) %>%
    filter(row_number() < 50) %>%
    mutate(alpha_rank = row_number(), cumalpha = c(0, head(cumsum(alpha), -1))) %>%
    mutate(in_cs = cumalpha < 0.95) %>%
    mutate(active_cs = component %in% names(res$fit$sets$cs)) %>%
    left_join(res$ora) %>%
    left_join(gs$geneSet$geneSetDes)

  return(credible.set.summary)
}

get_gene_set_summary = function(res){
  gs <- genesets[[res$db]]
  #' map each gene set to the component with top alpha
  #' report pip
  res$fit$pip %>% 
    as_tibble(rownames='geneSet') %>%
    rename(pip=value) %>%
    mutate(beta=colSums(res$fit$alpha * res$fit$mu)) %>%
    left_join(res$ora) %>%
    left_join(gs$geneSet$geneSetDes)
}

pack_group = function(tbl){
    components <- tbl$component
    unique.components <- unique(components)
    start <- match(unique.components, components)
    end <- c(tail(start, -1) - 1, length(components))
    res <- tbl %>% select(-c(component)) %>% kbl()
    for(i in 1:length(unique.components)){
      res <- pack_rows(res, unique.components[i], start[i], end[i])
    }
    return(res)
}

report_susie_credible_sets = function(tbl,
                                      target_coverage=0.95,
                                      max_coverage=0.99,
                                      max_sets=10){
  tbl_filtered <-
    tbl %>%
    group_by(db, component) %>%
    arrange(db, component, desc(alpha)) %>%
    filter(cumalpha <= max_coverage, alpha_rank <= max_sets) %>%
    mutate(in_cs = cumalpha <= target_coverage) %>% ungroup()

  tbl_filtered %>%
    select(component, geneSet, description, alpha, beta, beta.se, pValueHypergeometric, overlap, geneSetSize, oddsRatio) %>%
    dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
    pack_group %>%
    column_spec(c(4), color=ifelse(tbl_filtered$beta >0, 'green', 'red')) %>%
    kableExtra::kable_styling()
}
```

## NMF

```{r fit.nfm.gsea}
ix  <- order(nmf$fl$pve[-1], decreasing = T) + 1  # exclude first topic
Y <- purrr::map(ix, ~get_y(nmf$fl$L.lfsr[,.x], 1e-5))
names(Y) = paste0('topic_', ix)

nmf.gobp <- xfun::cache_rds({
  susie.args <- list(L=10, maxit=200, verbose=T)
  purrr::map(Y, ~do_logistic_susie(.x, 'gobp', susie.args = susie.args))},
  dir = 'cache/deng_example/', file='nmf.gobp')

nmf.gomf <- xfun::cache_rds({
  susie.args <- list(L=10, maxit=200, verbose=T)
  purrr::map(Y, ~do_logistic_susie(.x, 'gomf', susie.args = susie.args))},
  dir = 'cache/deng_example/', file='nmf.gomf')

nmf.kegg <- xfun::cache_rds({
  susie.args <- list(L=10, maxit=200, verbose=T)
  purrr::map(Y, ~do_logistic_susie(.x, 'kegg', susie.args = susie.args))},
  dir = 'cache/deng_example/', file='nmf.kegg')

nmf.fits <- mget(ls(pattern='^nmf.+'))
names(nmf.fits) <- purrr::map_chr(names(nmf.fits), ~str_split(.x, '\\.')[[1]][2])
```

### Thresholds

```{r threshold.sensitivity, eval=FALSE}
mean.gene.prop = function(l){
  purrr::map_dbl(3:10, ~get_y(l, 10^(-.x)) %>% mean())
}

y.mean.thresh <- purrr::map(2:10, ~mean.gene.prop(nmf$fl$L.lfsr[,.x]))

plot(3:10, y.mean.thresh[[2]]/y.mean.thresh[[2]][1],
  type='line',
  ylim = c(0.5, 1),
  main = 'sensitiviy to lfsr threshold',
  ylab = 'prop genes relative to 1e-3 threshold',
  xlab = '-log10(threshold)')

for(i in 1:length(y.mean.thresh)){
  lines(3:10, y.mean.thresh[[i]]/y.mean.thresh[[i]][1])
}
```


```{r nmf.tables, results="asis"}
library(htmltools)

make_susie_html_table = function(fits, db, topic){
  fits %>%
    pluck(db) %>%
    pluck(topic) %>%
    get_credible_set_summary() %>%
    filter(active_cs, in_cs) %>%
    report_susie_credible_sets(target_coverage = 0.95, max_coverage = 0.95)
}

possibly_make_susie_html_table = possibly(
  make_susie_html_table, otherwise="nothing to report...")

for(topic in names(Y)){
  cat("\n") 
  cat("###", topic, "\n") # Create second level headings with the names.
  
  for(db in names(genesets)){
    cat("####", db, "\n") # Create second level headings with the names.
    possibly_make_susie_html_table(nmf.fits, db, topic) %>% print()
    cat("\n")
  }
}
```

## SNMF

```{r fit.snfm.gsea}
ix  <- order(snmf$fl$pve[-1], decreasing = T) + 1  # exclude first topic
Y.snmf <- purrr::map(ix, ~get_y(snmf$fl$L.lfsr[,.x], 1e-5))
names(Y.snmf) = paste0('topic_', ix)

snmf.gobp <- xfun::cache_rds({
  susie.args <- list(L=10, maxit=200, verbose=T)
  purrr::map(Y.snmf, ~do_logistic_susie(.x, 'gobp', susie.args = susie.args))},
  dir = 'cache/deng_example/', file='snmf.gobp', rerun=T)

snmf.gomf <- xfun::cache_rds({
  susie.args <- list(L=10, maxit=200, verbose=T)
  purrr::map(Y.snmf, ~do_logistic_susie(.x, 'gomf', susie.args = susie.args))},
  dir = 'cache/deng_example/', file='snmf.gomf')

snmf.kegg <- xfun::cache_rds({
  susie.args <- list(L=10, maxit=200, verbose=T)
  purrr::map(Y.snmf, ~do_logistic_susie(.x, 'kegg', susie.args = susie.args))},
  dir = 'cache/deng_example/', file='snmf.kegg')

snmf.fits <- mget(ls(pattern='^snmf.+'))
names(snmf.fits) <- purrr::map_chr(names(snmf.fits), ~str_split(.x, '\\.')[[1]][2])
```


```{r snmf.tables, results="asis"}
for(topic in names(Y.snmf)){
  cat("\n") 
  cat("###", topic, "\n") # Create second level headings with the names.
  
  for(db in names(genesets)){
    cat("####", db, "\n") # Create second level headings with the names.
    possibly_make_susie_html_table(snmf.fits, db, topic) %>% print()
    cat("\n")
  }
}
```

