---
title: "human_chimp_eb_de_example"
author: "karltayeb"
date: "2022-04-11"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(
  root.dir = '/project2/gilad/ktayeb/logistic-susie-gsea/'
)
knitr::opts_chunk$set(
  comment = '',
  message=FALSE, warning=FALSE,
  root.dir = '/project2/gilad/ktayeb/logistic-susie-gsea/'
)
```

## Introduction

```{r imports}
library(tidyverse)
source('code/utils.R')
source('code/logistic_susie_vb.R')
source('code/logistic_susie_veb_boost.R')
source('code/load_gene_sets.R')
```

```{r standardize.data}
de <- readRDS('data/human_chimp_eb/big.df.rds')

hs <- org.Hs.eg.db::org.Hs.eg.db
gene_symbols <- unique(de$gene)
symbol2entrez <- AnnotationDbi::select(
  hs, keys=gene_symbols,
  columns=c('ENTREZID', 'SYMBOL'),
  keytype = 'SYMBOL')

add_names = function(l, n){
  names(l) <- n
  return(l)
}

standardized.de <- de %>%
  rename(SYMBOL=gene) %>%
  left_join(symbol2entrez, by='SYMBOL') %>%
  relocate(ENTREZID, .after=SYMBOL) %>%
  mutate(  # set default columns
    beta = dream.logFC,
    se = dream.SE,
    threshold.on = dream.p.val
  ) %>%
  group_by(celltype) %>%
  group_map(~ .x, .keep = T) %>%
  add_names(map_chr(., ~pluck(.x, 'celltype')[1]))
```

```{r load.gene.sets}
# load genesets
gobp <- loadGeneSetX('geneontology_Biological_Process', min.size=50)  # just huge number of gene sets
gobp_nr <- loadGeneSetX('geneontology_Biological_Process_noRedundant', min.size=1)
gomf <- loadGeneSetX('geneontology_Molecular_Function', min.size=1)
kegg <- loadGeneSetX('pathway_KEGG', min.size=1)
reactome <- loadGeneSetX('pathway_Reactome', min.size=1)
wikipathway_cancer <- loadGeneSetX('pathway_Wikipathway_cancer', min.size=1)
wikipathway <- loadGeneSetX('pathway_Wikipathway', min.size=1)

genesets <- list(
  gobp=gobp,
  gobp_nr=gobp_nr,
  gomf=gomf,
  kegg=kegg,
  reactome=reactome,
  wikipathway_cancer=wikipathway_cancer,
  wikipathway=wikipathway
)
```

```{r fit.functions}
prep_binary_data = function(gs, dat, thresh) {
  # get common genes as background
  gs.genes <- rownames(gs$X)
  
  # filter gene list
  y <- dat %>%
    filter(ENTREZID %in% gs.genes, !is.na(threshold.on)) %>%
    mutate(geneList = as.integer(threshold.on < thresh)) %>%
    select(ENTREZID, geneList) %>%
    tibble2namedlist()

  # filter gene sets
  y.genes <- names(y)
  test.genes <- intersect(gs.genes, y.genes)
  X <- gs$X[test.genes,]
  bad.cols <- BiocGenerics::colSums(X)
  bad.cols <- (bad.cols == 0) | bad.cols == length(test.genes)
  X <- X[, which(!bad.cols)]
  
  return(list(y=y, X=X))
}

do_logistic_susie = function(experiment,
                             db,
                             thresh,
                             susie.args=NULL){
  gs <- genesets[[db]]
  dat <- standardized.de[[experiment]]
  u <- prep_binary_data(gs, dat, thresh)  # subset to common genes
  
  if(is.null(susie.args)){  # default SuSiE args
    susie.args = list(
      L=10, init.intercept=0, verbose=1, maxit=500, standardize=FALSE)
  }
  vb.fit <- exec(logistic.susie, u$X, u$y, !!!susie.args)
  res = tibble(
    experiment=experiment,
    db=db,
    thresh=thresh,
    fit=list(vb.fit)
  )
  return(res)
}

do_logistic_susie_veb = function(experiment,
                                 db,
                                 thresh,
                                 susie.args=NULL){
  gs <- genesets[[db]]
  dat <- standardized.de[[experiment]]
  u <- prep_binary_data(gs, dat, thresh)  # subset to common genes
  
  if(is.null(susie.args)){  # default SuSiE args
    susie.args = list(L=10)
  }
  vb.fit <- exec(logistic.susie.veb.boost, u$X, u$y, !!!susie.args)
  res = tibble(
    experiment=experiment,
    db=db,
    thresh=thresh,
    fit=list(vb.fit)
  )
  return(res)
}

do_ora = function(experiment,
                  db,
                  thresh){
  
  gs <- genesets[[db]]
  dat <- standardized.de[[experiment]]
  u <- prep_binary_data(gs, dat, thresh)  # subset to common genes
  
  do_fet = function(overlap, geneListSize, geneSetSize, nGenes){
    ct <- matrix(c(
      overlap,
      geneListSize-overlap,
      geneSetSize-overlap,
      nGenes - geneSetSize - geneListSize + overlap), nr=2)
    return(fisher.test(ct)$p.value)
  }
  
  do_hyper = function(overlap, geneListSize, geneSetSize, nGenes){
    # genes in list = white balls, not in list = black balls
    # draw k balls w/o replacement where k is the size of the gene set
    # is the overlap we see with our gene set extreme/unlikely?
    return(phyper(
      max(0, overlap - 1),  # p(X >= overlap) = p(X > overlap - 1)
      geneListSize,
      nGenes - geneListSize,
      geneSetSize,
      lower.tail = FALSE))
  }
  
  ora <- tibble(
      geneSet = colnames(u$X),
      geneListSize = sum(u$y),
      geneSetSize = BiocGenerics::colSums(u$X),
      overlap = (u$y %*% u$X)[1,],
      nGenes = length(u$y),
      propInList = overlap / geneListSize,
      propInSet = overlap / geneSetSize,
      oddsRatio = (overlap / (geneListSize - overlap)) / (
        (geneSetSize - overlap) / (nGenes - geneSetSize + overlap))
    ) %>%
    rowwise() %>%
    mutate(
      pHypergeometric = do_hyper(overlap, geneListSize, geneSetSize, nGenes),
      pFishersExact = do_fet(overlap, geneListSize, geneSetSize, nGenes)
    ) %>% 
    ungroup()
  
  res = tibble(
    experiment=experiment,
    db=db,
    thresh=thresh,
    fit=list(ora)
  )
  return(res)
}
```

```{r summary.functions}
get_credible_set_summary = function(res){
  #' report top 50 elements in cs
  beta <- t(res$mu) %>%
    data.frame() %>%
    rownames_to_column(var='geneSet') %>%
    rename_with(~str_replace(., 'X', 'L')) %>%
    rename(L1 = 2) %>%  # rename deals with L=1 case
    pivot_longer(starts_with('L'), names_to='component', values_to = 'beta') 
  se <- t(sqrt(res$mu2 - res$mu^2)) %>%
     data.frame() %>%
      rownames_to_column(var='geneSet') %>%
      rename_with(~str_replace(., 'X', 'L')) %>%
      rename(L1 = 2) %>%  # rename deals with L=1 case
      pivot_longer(starts_with('L'), names_to='component', values_to = 'beta.se')
  
  credible.set.summary <- t(res$alpha) %>%
    data.frame() %>%
    rownames_to_column(var='geneSet') %>%
    rename_with(~str_replace(., 'X', 'L')) %>%
    rename(L1 = 2) %>%  # rename deals with L=1 case
    pivot_longer(starts_with('L'), names_to='component', values_to = 'alpha') %>%
    left_join(beta) %>%
    left_join(se) %>%
    arrange(component, desc(alpha)) %>%
    dplyr::group_by(component) %>%
    filter(row_number() < 50) %>%
    mutate(alpha_rank = row_number(), cumalpha = c(0, head(cumsum(alpha), -1))) %>%
    mutate(in_cs = cumalpha < 0.95) %>%
    mutate(active_cs = component %in% names(res$sets$cs))
  return(credible.set.summary)
}

get_gene_set_summary = function(res){
  #' map each gene set to the component with top alpha
  #' report pip
  res$pip %>% 
    as_tibble(rownames='geneSet') %>%
    rename(pip=value) %>%
    mutate(beta=colSums(res$alpha * res$mu))
}

pack_group = function(tbl){
    components <- tbl$component
    unique.components <- unique(components)
    start <- match(unique.components, components)
    end <- c(tail(start, -1) - 1, length(components))
    res <- tbl %>% select(-c(component)) %>% kbl()
    for(i in 1:length(unique.components)){
      res <- pack_rows(res, unique.components[i], start[i], end[i])
    }
    return(res)
}

report_susie_credible_sets = function(tbl,
                                      target_coverage=0.95,
                                      max_coverage=0.99,
                                      max_sets=10){
  tbl_filtered <-
    tbl %>%
    group_by(db, component) %>%
    arrange(db, component, desc(alpha)) %>%
    filter(cumalpha <= max_coverage, alpha_rank <= max_sets) %>%
    mutate(in_cs = cumalpha <= target_coverage) %>% ungroup()

  tbl_filtered %>%
    select(component, geneSet, description, alpha, beta, beta.se, pValueHypergeometric, overlap, geneSetSize, oddsRatio) %>%
    dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
    pack_group %>%
    column_spec(c(4), color=ifelse(tbl_filtered$beta >0, 'green', 'red')) %>%
    kableExtra::kable_styling()
}
```

```{r test}
db = 'gomf'
experiment = 'Acinar cells'
thresh = 1e-3

vb.fit <- do_logistic_susie(experiment, db, thresh)
veb.fit <- do_logistic_susie_veb(experiment, db, thresh)

vb.fit$fit[[1]] %>% get_credible_set_summary()
ora <- do_ora(experiment, db, thresh) 

res <- purrr::map_dfr(head(names(standardized.de), 3), ~do_logistic_susie(.x, db, thresh))
res %>% mutate(
  cs.summary = map(fit, get_credible_set_summary),
  gs.summary = map(fit, get_gene_set_summary)
)
```


```{r}
do_logistic_susie_cached = function(db, thresh){
  res <- xfun::cache_rds({
    purrr::map_dfr(names(standardized.de), ~do_logistic_susie(.x, db, thresh))
  }, dir = 'cache/human_chimp_eb_de_example/', file=paste0('logistic_susie_', db, '_', thresh))
}

do_ora_cached = function(db, thresh){
  res <- xfun::cache_rds({
    purrr::map_dfr(names(standardized.de), ~do_ora(.x, db, thresh))
  }, dir = 'cache/human_chimp_eb_de_example/', file=paste0('ora_', db, '_', thresh))
}

do_logistic_susie_cached('gobp', 1e-3)
do_logistic_susie_cached('gomf', 1e-3)
do_logistic_susie_cached('kegg', 1e-3)

do_ora_cached('gobp', 1e-3)
do_ora_cached('gomf', 1e-3)
do_ora_cached('kegg', 1e-3)
```




