---
title: "ser_susie"
author: "Karl Tayeb"
date: "2022-11-15"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r setup}
library(tidyverse)
library(kableExtra)
library(targets)
devtools::load_all('~/R/logisticsusie/')

example <- readRDS('data/yusha_sc_tumor/pdac_example.rds')
bindata <- with(example, gseasusie::prep_binary_data(genesets, data, thresh = 0.01))
gs_names <- colnames(bindata$X)
n_gene_sets <- dim(bindata$X)[2]
```


### $L=5$, $n=500$
```{r fitting_l5n500}
tar_load(yusha_ibss_l5_n500)
fits <- yusha_ibss_l5_n500

fits$fit$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()


ibss_monitor_convergence(fits$ibss_vb)
fits$ibss_vb$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()


ibss_monitor_convergence(fits$ibss_uvb)
fits$ibss_uvb$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()
```

### $L=5$, $n=100$

```{r fitting_l5n100}
tar_load(yusha_ibss_l5_n100)
fits <- yusha_ibss_l5_n100

fits$fit$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()


ibss_monitor_convergence(fits$ibss_vb)
fits$ibss_vb$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()


ibss_monitor_convergence(fits$ibss_uvb)
fits$ibss_uvb$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()
```

### $L=3$, $n=500$

```{r fitting l3n500}
tar_load(yusha_ibss_l3_n500)
fits <- yusha_ibss_l3_n500

fits$fit$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()


ibss_monitor_convergence(fits$ibss_vb)
fits$ibss_vb$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()


ibss_monitor_convergence(fits$ibss_uvb)
fits$ibss_uvb$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()
```

### $L=3$, $n=100$

```{r fitting l3n100}
tar_load(yusha_ibss_l3_n100)
fits <- yusha_ibss_l3_n100

fits$fit$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()


ibss_monitor_convergence(fits$ibss_vb)
fits$ibss_vb$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()


ibss_monitor_convergence(fits$ibss_uvb)
fits$ibss_uvb$alpha  %>%
  cs_tbl2() %>% 
  rowwise() %>% 
  mutate(cs = list(head(cs, 10)), prob = list(head(prob, 10))) %>%
  kbl() %>% kable_styling()
```

